package org.dalnservice.classes;

import java.util.HashMap;
import java.util.List;

/**
 * Created by Shakib on 8/4/2016.
 */
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_EMPTY)
@DynamoDBTable(tableName = "")
public class Post {
    private String postId, title, email, license, description, hiddenDescription, identifierUri, dateAccessioned,
            dateAvailable, dateCreated, dateIssued, dateSubmitted, rightsConsent, rightsRelease;
    private long dateIssuedTimestamp;
    private List<String> contributorAuthor, contributorInterviewer, creatorGender, creatorRaceEthnicity, creatorClass,
            creatorYearOfBirth, coverageSpatial, coveragePeriod, coverageRegion, coverageStateProvince,
            coverageNationality, language, subject;
    private boolean isPostNotApproved, areAllFilesUploaded, isPostRejected;
    private List<HashMap<String, String>> assetList;

    public Post() {
    }

    @DynamoDBHashKey(attributeName = "PostId")
    // @DynamoDBIndexHashKey(globalSecondaryIndexName = "PostId-index",
    // attributeName = "PostId")
    @DynamoDBAutoGeneratedKey
    public String getPostId() {
        return postId;
    }

    public void setPostId(String postId) {
        this.postId = postId;
    }

    @DynamoDBAttribute(attributeName = "title")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute(attributeName = "isPostRejected")
    public boolean getIsPostRejected() {
        return isPostRejected;
    }

    public void setIsPostRejected(boolean isPostRejected) {
        this.isPostRejected = isPostRejected;
    }

    @DynamoDBAttribute(attributeName = "email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName = "license")
    public String getLicense() {
        return license;
    }

    public void setLicense(String license) {
        this.license = license;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "hiddenDescription")
    public String getHiddenDescription() {
        return hiddenDescription;
    }

    public void setHiddenDescription(String hiddenDescription) {
        this.hiddenDescription = hiddenDescription;
    }

    @DynamoDBAttribute(attributeName = "identifierUri")
    public String getIdentifierUri() {
        return identifierUri;
    }

    public void setIdentifierUri(String identifierUri) {
        this.identifierUri = identifierUri;
    }

    @DynamoDBAttribute(attributeName = "dateAccessioned")
    public String getDateAccessioned() {
        return dateAccessioned;
    }

    public void setDateAccessioned(String dateAccessioned) {
        this.dateAccessioned = dateAccessioned;
    }

    @DynamoDBAttribute(attributeName = "dateAvailable")
    public String getDateAvailable() {
        return dateAvailable;
    }

    public void setDateAvailable(String dateAvailable) {
        this.dateAvailable = dateAvailable;
    }

    @DynamoDBAttribute(attributeName = "dateCreated")
    public String getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    @DynamoDBAttribute(attributeName = "dateSubmitted")
    public String getDateSubmitted() {
        return dateSubmitted;
    }

    public void setDateSubmitted(String dateSubmitted) {
        this.dateSubmitted = dateSubmitted;
    }

    @DynamoDBAttribute(attributeName = "dateIssuedTimestamp")
    public long getDateIssuedTimestamp() {
        return dateIssuedTimestamp;
    }

    public void setDateIssuedTimestamp(long dateIssuedTimestamp) {
        this.dateIssuedTimestamp = dateIssuedTimestamp;
    }

    @DynamoDBAttribute(attributeName = "dateIssued")
    public String getDateIssued() {
        return dateIssued;
    }

    public void setDateIssued(String dateIssued) {
        this.dateIssued = dateIssued;
    }

    @DynamoDBAttribute(attributeName = "rightsConsent")
    public String getRightsConsent() {
        return rightsConsent;
    }

    public void setRightsConsent(String rightsConsent) {
        this.rightsConsent = rightsConsent;
    }

    @DynamoDBAttribute(attributeName = "rightsRelease")
    public String getRightsRelease() {
        return rightsRelease;
    }

    public void setRightsRelease(String rightsRelease) {
        this.rightsRelease = rightsRelease;
    }

    @DynamoDBAttribute(attributeName = "contributorAuthor")
    public List<String> getContributorAuthor() {
        return contributorAuthor;
    }

    public void setContributorAuthor(List<String> contributorAuthor) {
        this.contributorAuthor = contributorAuthor;
    }

    @DynamoDBAttribute(attributeName = "contributorInterviewer")
    public List<String> getContributorInterviewer() {
        return contributorInterviewer;
    }

    public void setContributorInterviewer(List<String> contributorInterviewer) {
        this.contributorInterviewer = contributorInterviewer;
    }

    @DynamoDBAttribute(attributeName = "creatorGender")
    public List<String> getCreatorGender() {
        return creatorGender;
    }

    public void setCreatorGender(List<String> creatorGender) {
        this.creatorGender = creatorGender;
    }

    @DynamoDBAttribute(attributeName = "creatorRaceEthnicity")
    public List<String> getCreatorRaceEthnicity() {
        return creatorRaceEthnicity;
    }

    public void setCreatorRaceEthnicity(List<String> creatorRaceEthnicity) {
        this.creatorRaceEthnicity = creatorRaceEthnicity;
    }

    @DynamoDBAttribute(attributeName = "creatorClass")
    public List<String> getCreatorClass() {
        return creatorClass;
    }

    public void setCreatorClass(List<String> creatorClass) {
        this.creatorClass = creatorClass;
    }

    @DynamoDBAttribute(attributeName = "creatorYearOfBirth")
    public List<String> getCreatorYearOfBirth() {
        return creatorYearOfBirth;
    }

    public void setCreatorYearOfBirth(List<String> creatorYearOfBirth) {
        this.creatorYearOfBirth = creatorYearOfBirth;
    }

    @DynamoDBAttribute(attributeName = "coverageSpatial")
    public List<String> getCoverageSpatial() {
        return coverageSpatial;
    }

    public void setCoverageSpatial(List<String> coverageSpatial) {
        this.coverageSpatial = coverageSpatial;
    }

    @DynamoDBAttribute(attributeName = "coveragePeriod")
    public List<String> getCoveragePeriod() {
        return coveragePeriod;
    }

    public void setCoveragePeriod(List<String> coveragePeriod) {
        this.coveragePeriod = coveragePeriod;
    }

    @DynamoDBAttribute(attributeName = "coverageRegion")
    public List<String> getCoverageRegion() {
        return coverageRegion;
    }

    public void setCoverageRegion(List<String> coverageRegion) {
        this.coverageRegion = coverageRegion;
    }

    @DynamoDBAttribute(attributeName = "coverageStateProvince")
    public List<String> getCoverageStateProvince() {
        return coverageStateProvince;
    }

    public void setCoverageStateProvince(List<String> coverageStateProvince) {
        this.coverageStateProvince = coverageStateProvince;
    }

    @DynamoDBAttribute(attributeName = "coverageNationality")
    public List<String> getCoverageNationality() {
        return coverageNationality;
    }

    public void setCoverageNationality(List<String> coverageNationality) {
        this.coverageNationality = coverageNationality;
    }

    @DynamoDBAttribute(attributeName = "language")
    public List<String> getLanguage() {
        return language;
    }

    public void setLanguage(List<String> language) {
        this.language = language;
    }

    @DynamoDBAttribute(attributeName = "subject")
    public List<String> getSubject() {
        return subject;
    }

    public void setSubject(List<String> subject) {
        this.subject = subject;
    }

    @DynamoDBAttribute(attributeName = "isPostNotApproved")
    public boolean getIsPostNotApproved() {
        return isPostNotApproved;
    }

    public void setIsPostNotApproved(boolean isPostNotApproved) {
        this.isPostNotApproved = isPostNotApproved;
    }

    @DynamoDBAttribute(attributeName = "assetList")
    public List<HashMap<String, String>> getAssetList() {
        return assetList;
    }

    public void setAssetList(List<HashMap<String, String>> assetList) {
        this.assetList = assetList;
    }

    @DynamoDBAttribute(attributeName = "areAllFilesUploaded")
    public Boolean getAreAllFilesUploaded() {
        return areAllFilesUploaded;
    }

    public void setAreAllFilesUploaded(Boolean areAllFilesUploaded) {
        this.areAllFilesUploaded = areAllFilesUploaded;

    }
}